name:        mttt
version:     0.4.0
author:      "Adrián Lattes y David Díez"
description: "Please see the README"
homepage: "https://haztecaso.com/mttt/"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- array
- gloss

library:
  source-dirs: src

executables:
  mttt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -haddock
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt
    - parseargs

tests:
  mttt-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt
