name:                mttt
version:             0.1.0.0
# github:              "githubuser/mttt"
license:             GPLv3
author:              "Adrián Lattes y David Díez"
# maintainer:          "example@example.com"
# copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- array

library:
  source-dirs: src

executables:
  mttt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt

tests:
  mttt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt
