name:        mttt
version:     0.1.0.0
license:     GPLv3
author:      "Adrián Lattes y David Díez"
# maintainer:  "example@example.com"
# copyright:   "2020"
description: "Please see the README"
# github:      "githubuser/mttt"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- array
- gloss

library:
  source-dirs: src

executables:
  mttt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt

tests:
  mttt-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt
