name:        mttt
version:     1.0.1
author:      "Adrián Lattes y David Díez"
description: "Entrega de programación declarativa: implementación en Haskell del juego `meta tres en raya`. En el archivo readme.md hay más información sobre el juego y el código."
git: "https://git.haztecaso.com/mttt"
homepage: "https://git.haztecaso.com/mttt/about/"

extra-source-files:
- readme.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

dependencies:
- base >= 4.7 && < 5
- array
- gloss

library:
  source-dirs: src

executables:
  mttt:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -haddock
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwarn-tabs
    - -fwarn-orphans
    - -fwarn-incomplete-patterns
    - -fwarn-unused-imports
    dependencies:
    - mttt
    - parseargs

tests:
  mttt-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mttt
